name: appdetest
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.7
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  image_picker: ^0.8.7+6
  intl: ^0.18.1 
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/bg.jpg
    - assets/images/bg1.jpg
    - assets/images/bg2.jpg 
    - assets/images/bg3.jpg
    - assets/images/bg4.jpg 
    - assets/images/bg5.jpg
    - assets/data/users.json
    - assets/data/expenses.json
    - assets/data/notifications.json
    - assets/data/notifications_manager.json

